apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: prod-low-priority
value: 10000
globalDefault: false
preemptionPolicy: Never
description: "This class is used for low priority pods."
