apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: prod-high-priority
value: 1000000
globalDefault: false
preemptionPolicy: PreemptLowerPriority
description: "This class is used for hight priority pods."
