apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: postgres
  name: postgres
  namespace: auction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgres
    spec:
      securityContext:
        fsGroup: 7777
      volumes:
      - name: db-data-volume
        hostPath:
          path: /db-data
          type: DirectoryOrCreate
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 7777:7777 /var/lib/postgresql/data"]
        securityContext:
          runAsUser: 0
          runAsNonRoot: false
        volumeMounts:
        - name: db-data-volume
          mountPath: /var/lib/postgresql/data
      containers:
      - image: postgres:15-alpine
        name: postgresql
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data-volume
        env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: db-configmap
              key: DB_USER
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: db-configmap
              key: DB_NAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password
              key: DB_PASS
        resources: {}
status: {}
