apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: auction-deploy
  name: auction-deploy
  namespace: auction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auction-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: auction-deploy
    spec:
      imagePullSecrets:
      - name: docker-hub-secret
      containers:
      - image: kostalip/auction:auction-service-v1
        name: auction
        ports:
        - containerPort: 8400
        env:
        - name: SERVER_PORT
          value: "8400"
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: db-configmap
              key: DB_USER
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-configmap
              key: DB_NAME
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-configmap
              key: DB_PORT
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-configmap
              key: DB_HOST
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password
              key: DB_PASS
        resources: {}
status: {}
