apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: admission-controller-deploy
  name: admission-controller
  namespace: mutating-webhook
spec:
  ports:
  - port: 443
    name: service-port
    protocol: TCP
    targetPort: target-port
  selector:
    app: admission-controller-deploy
  type: ClusterIP
status:
  loadBalancer: {}
