apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: auction-deploy
  name: auction-service
  namespace: auction
spec:
  ports:
  - port: 8400
    protocol: TCP
    targetPort: 8400
  selector:
    app: auction-deploy
  type: ClusterIP
status:
  loadBalancer: {}
