apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: auction
spec:
  limits:
  - type: Container
    default:
      memory: 512Mi
    defaultRequest:
      memory: 256Mi
      cpu: 150m
