apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: auction-deploy
  name: auction-deploy
  namespace: auction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auction-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: auction-deploy
    spec:
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 7777:7777 /var/log/auction"]
        securityContext:
          runAsUser: 0
          runAsNonRoot: false
        volumeMounts:
        - name: auction-logs
          mountPath: /var/log/auction
      volumes:
      - name: auction-logs
        hostPath:
          path: /var/log/auction
          type: DirectoryOrCreate
      imagePullSecrets:
      - name: docker-hub-secret
      containers:
      - image: kostalip/auction:auction-service-v4
        name: auction
        volumeMounts:
        - name: auction-logs
          mountPath: /var/log/auction
        ports:
        - containerPort: 8400
        env:
        - name: SERVER_PORT
          value: "8400"
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: db-configmap
              key: DB_USER
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-configmap
              key: DB_NAME
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-configmap
              key: DB_PORT
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-configmap
              key: DB_HOST
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password
              key: DB_PASS
        resources: {}
status: {}
