apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: auth-deploy
  name: auth-service
  namespace: auction
spec:
  ports:
  - port: 8880
    protocol: TCP
    targetPort: 8880
  selector:
    app: auth-deploy
  type: ClusterIP
status:
  loadBalancer: {}
