apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: bank-account-deploy
  name: bank-account
  namespace: auction
spec:
  ports:
  - port: 8200
    protocol: TCP
    targetPort: 8200
  selector:
    app: bank-account-deploy
  type: ClusterIP
status:
  loadBalancer: {}
