apiVersion: v1
data:
  DB_HOST: postgres-service
  DB_NAME: auctionDB
  DB_USER: auctionUser
  DB_PORT: "5432"

  SPRING_SQL_INIT_MODE: "always"
  SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: "true"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: db-configmap
  namespace: auction
