apiVersion: v1
data:
  DB_HOST: postgres-service
  DB_NAME: auctionDB
  DB_USER: auctionUser
  DB_PORT: "5432"

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: db-configmap
  namespace: auction
