apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- admission-controller-deployment.yaml
- admission-controller-service.yaml
- auction-deployment.yaml
- auction-ingress.yaml
- auction-service.yaml
- auth-deployment.yaml
- auth-service.yaml
- bank-account-deployment.yaml
- bank-account-service.yaml
- db-configmap.yaml
- db-password-secret.yaml
- docker-hub-secret.yaml
- kustomization.yaml
- mutating-webhook-configuration.yaml
- postgres-service.yaml
- postgres-test-deployment.yaml
- product-deployment.yaml
- product-service.yaml
- user-deployment.yaml
- user-service.yaml
- webhook-csr.yaml
