apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: user-deploy
  name: user-service
  namespace: auction
spec:
  ports:
  - port: 8770
    protocol: TCP
    targetPort: 8770
  selector:
    app: user-deploy
  type: ClusterIP
status:
  loadBalancer: {}
